version: "3.3"

services: 
  app: 
    build: 
      context: .
      dockerfile: Dockerfile.deb
    image: $USER/dts-explorer-client:0.0.1
    volumes:
      - .:/src:cached
      - node_modules:/src/node_modules:cached
    ports:
      - "4200:4200"
      - "7020:7020"
      - "7357:7357"
      - "9222:9222"

volumes:
  node_modules: